#!/usr/bin/perl
use strict;
use warnings;

use lib "./SWGetopt/lib";
use lib "../lib/perl";

use SWGetopt;

my (%Options);

# Need to work on this but this will be a crude
# implementation of a package manager for our program.
# Right now it's just a test of the getopt module.

GetOptions(\%Options, "length=i", "file=s", "verbose")
        or die("Error in command line arguments\n");

if (exists($Options{"verbose"})) {
        print "Woo\n";
}

# Options baseing it off aptitude, pip, and cpanm
# install (package) 
# remove (package)
# 	Need to check dependencies
# search/list  (local and remote)
# info/show (package)
#	dependencies, info about package, details of install/uninstall
# update (package) (all)
# Show whats out of date???
# Need to be able to set remote site
# Need to be able to set destination dir 
#	keep in mind may have (user vs system)
# Need to handle versions
# Need to create/maintain an archive

=head1 EXAMPLES

Basic usage:

=over 8

=item
spm install getopt            Install the getopt module.

=item
spm remove getopt             Uninstall the getopt module.

=item
spm info getopt               Display information about a module.

=item
spm list                      List Available modules.

=item
spm list get                  List Available modules that contain get.

=back

=cut
