#!/usr/bin/perl
use strict;
use warnings;
use getopt;

my (%Options);

# Need to work on this but this will be a crude
# implementation of a package manager for our program.
# Right now it's just a test of the getopt module.

GetOptions(\%Options, "length=i", "file=s", "verbose")
        or die("Error in command line arguments\n");

if (exists($Options{"verbose"})) {
        print "Woo\n";
}

