/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <getopt.h>

#include "Parser.h"
#include "Printer.h"
#include "Absyn.h"

#define VERSION "0.0"

int print = -1;
int help = -1;
int critic = -1;
int libdir = -1;
int incdir = -1;
int outfile = -1;
int version = -1;
int opt = 0;


static struct option long_options[] = {
	{"print",	no_argument,		0,	'p' },
	{"help",	no_argument,		0,	'h' },
	{"critic",	no_argument,		0,	'C' },
	{"include",	required_argument,	NULL,	'I' },
	{"lib",		required_argument,	NULL,	'L' },
	{"output",	required_argument,	NULL,	'o' },
	{"version",	no_argument,		NULL,	'v' },
	{0,		0,			0,	0 }
};

void print_version(char *name) {
	printf("%s Version: %s\n", name, VERSION);
/*
	printf("%s_config_path: %s\n", name, config_path);
	printf("%s_config_file: %s\n", name, config_file);
	printf("%s_include_path: %s\n", name, include_path);
	printf("%s_lib_path: %S\n", name, lib_path);
	printf("%s_critic_path: %s\n", name, critic_path);
*/
}

void print_usage(char *name) {
	printf("Usage: %s [OPTIONS] [INFILE]\n", name);
	printf("\tEvaluate the file INFILE.  If no file is given, read ");
	printf("from stdin.\n");
	printf("Available Options:\n");
	printf("\t-p --print\n\t\tParse the file and then print it in the ");
	printf("standard format.\n");
	printf("\t-h --help\n\t\tThis usage information.\n");
	printf("\t-C --critic\n\t\tPrint feedback on the submitted code.\n");
	printf("\t-I --include=DIR\n\t\tSpecify a directory to search for ");
	printf("include files.\n");
	printf("\t-L --lib=DIR\n\t\tSpecify a directory to search for ");
	printf("inheritables.\n");
	printf("\t-o --output=FILE\n\t\tSpecify a filename to compile ");
	printf("the code to.\n");
	printf("\t-v --version\n\t\tPrint Version information.\n");
}

int main(int argc, char ** argv) {
   FILE *input;
   Program parse_tree;
   int long_index = 0;

   while ((opt = getopt_long(argc, argv, "hopvL:I:C:", long_options,
      &long_index)) != -1) {
      switch (opt) {
         case 'C':
            break;
         case 'L':
            break;
         case 'I':
            break;
         case 'o':
            break;
         case 'p':
            break;
         case 'v':
            print_version(argv[0]);
            return 0;
            break;
         default:
            print_usage(argv[0]);
            return 0;
      }
   }

   if (argc > 1) {
      input = fopen(argv[1], "r");
      if (!input) {
         fprintf(stderr, "Error opening input file.\n");
         exit(1);
      }
   } else {
      input = stdin;
   }

   /* The default entry point is used. For other options see Parser.h */
   parse_tree = pProgram(input);
   if (parse_tree) {
      printf("\nParse Succesful!\n");
      printf("\n[Abstract Syntax]\n");
      printf("%s\n\n", showProgram(parse_tree));
      printf("[Linearized Tree]\n");
      printf("%s\n\n", printProgram(parse_tree));
      return 0;
   }

   return 1;
}

